FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN apt-get update \
	&& apt-get install -y --no-install-recommends build-essential \
	&& pip install --no-cache-dir -r requirements.txt \
	&& apt-get purge -y --auto-remove build-essential \
	&& rm -rf /var/lib/apt/lists/*
COPY app ./app
COPY data ./data
EXPOSE 8087
ENTRYPOINT ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8087"]
